name: Generate Monochrome Snake

on:
  schedule:
    # Roda todo dia à meia-noite
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      # Pega o conteúdo do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera a cobra monocromática
      - name: Generate Monochrome Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Modo claro: cobra preta, quadrados de contribuição cinza
            dist/github-snake-light.svg?color_snake=000000&color_dots=DDDDDD,BBBBBB,888888,333333
            # Modo escuro: cobra branca, quadrados de contribuição cinza
            dist/github-snake-dark.svg?color_snake=FFFFFF&color_dots=222222,444444,666666,888888

      # Commit automático dos arquivos gerados
      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update monochrome snake animation"
          file_pattern: "dist/*"

      # Publica na branch 'output'
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
